volumes:
  mongo-data:
    external: true
services:
  mongo:
    image: mongo:6
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
  fastapi:
    build:
      context: wanderwise
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./wanderwise:/app
    environment:
      DATABASE_URL: mongodb://root:password@mongo
      DATABASE_NAME: mongowise
      WAIT_HOSTS: mongo:27017
      SIGNING_KEY: ${SIGNING_KEY}
      API_KEY: ${API_KEY}
      PEXELS_KEY: ${PEXELS_KEY}
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_WANDERWISE_API_HOST: http://localhost:8000
